# Generated by Django 4.2.2 on 2023-06-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_address_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
