# Generated by Django 4.2.2 on 2023-06-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
