# Generated by Django 4.2.2 on 2023-06-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
